--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: tekton-hub
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      name: frontend-deploy
      labels:
        app: nodejs
    spec:
      containers:
        - name: frontend-deplpoy
          image: docker.io/puneet2147/test-frontend:v1
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: tekton-hub
  labels:
    app: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30004
  type: NodePort

---
apiVersion: v1
kind: Route
metadata:
  name: frontend-route
spec: 
  to:
    kind: Service
    name: frontend-svc
  tls:
    termination: edge
