--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: tekton-hub
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      name: ui
      labels:
        app: nodejs
    spec:
      containers:
        - name: ui
          image: docker.io/puneet2147/test-frontend:v1
          env:
            - name: REACT_APP_BACKEND_API
              valueFrom:
                configMapKeyRef:
                  name: ui
                  key: REACT_APP_BACKEND_API
          ports:
            - containerPort: 80
              protocol: TCP
