---
apiVersion: v1
kind: Route
metadata:
  name: frontend
  namespace: tekton-hub
spec: 
  to:
    kind: Service
    name: frontend
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge