apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: validation
  name: validation
  namespace: tekton-hub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
