apiVersion: v1
kind: Service
metadata:
  labels:
    app: validation
  name: validation
  namespace: tekton-hub
spec:
  type: ClusterIP
  selector:
    app: validation
  ports:
    - name: validation
      port: 5000
      protocol: TCP
      targetPort: 5000
